### ISSUE TITLE
1.一些灵活的适配

### ISSUE THREAD

**Issue by zhuweideng** [tiancanfei/ADCarouselView#1]
1、在执行 self.carouselView scrollToItemAtIndexPath 方法的地方包裹一层if (self.carouselImages.count) 使程序在addSubView 后赋值Imgs时不会崩溃。
2.在(void)setImgs:(NSArray *)imgs 添加  [self.carouselView reloadData];使collectionView 重新加载

**Comment by tiancanfei** [comment]
多谢提醒，已经修复了
